In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9, 0, 8], [6, 0, 5]])
print(b)

[[9 0 8]
 [6 0 5]]


In [6]:
#Get Dimension
a.ndim

1

In [7]:
#get shape
b.shape

(2, 3)

In [8]:
#get type
a.dtype

dtype('int64')

In [9]:
#get size
a.itemsize

8